[package]
name = "wxr_validator"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.37.2", features = ["encoding"] }
reqwest = { version = "0.11", features = ["blocking"] }
clap = { version = "4.5", features = ["derive"] }
